### ISSUE TITLE
Can't access mygottyip:9077

### ISSUE THREAD

**Issue by lavvy** [abdul/docker-gotty#1]
Please am i the only one having this issue.  I ran the container like explained

docker run -p 9077:8080 -it abdul/gotty [-w] /bin/bash
Open a browser at http://localhost:9077

But when i visit thegottyip:9077,  nothing shows . Please what am i not getting right ?

**Comment by abdul** [comment]
Please launch it as:

docker run -p 9077:8080 -it abdul/gotty -w /bin/bash (gives write capabilities to client)

Or 

docker run -p 9077:8080 -it abdul/gotty /bin/bash

**Comment by lavvy** [comment]
Please what am i doing wrong ???    http://163.172.179.9:9077

**Comment by lavvy** [comment]
![picture001](https://cloud.githubusercontent.com/assets/7013091/18191500/0bc36b06-7099-11e6-9743-0009372dd093.png)
![picture002](https://cloud.githubusercontent.com/assets/7013091/18191501/0c057244-7099-11e6-955d-d03274e5379e.png)

please see the pic. is there what else i have to activate, i dont know what is wrong

**Comment by lavvy** [comment]
ok i got it now, its the network .it is like it cant resolve through a docker container. am using a cloud vm now. though it is closing connection but atleast it now displays and hoping for more troubleshooting
